apiVersion: apps/v1
kind: Deployment
metadata:
  name: mondoo-example-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mondoo-example
  template:
    metadata:
      labels:
        app: mondoo-example
    spec:
      containers:
        - name: mondoo-example
          image: generosityroute/mondoo.example:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

