replicaCount: 3
image:
  repository: generosityroute/mondoo.example
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 20
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

