apiVersion: v1
kind: Service
metadata:
  name: {{ include "mondoo-example.fullname" . }}
  labels:
    {{- include "mondoo-example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "mondoo-example.name" . }}
