name: Build and Push Docker image

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build-docker]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Phase 2 repository
        uses: actions/checkout@v4

      - name: Checkout code from phase 1 repository
        uses: actions/checkout@v4
        with:
          repository: georg-nikola/mondoo-phase-1
          token: ${{ secrets.GITHUB_TOKEN }}
          path: mondoo-phase-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: generosityroute/mondoo.example:latest

      - name: Log out from Docker Hub
        run: docker logout
